name: Code Quality Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add UV to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Check code formatting with Ruff
        run: |
          echo "==> Checking code formatting with Ruff..."
          uv run --only-group dev ruff format --check .

      - name: Check linting with Ruff
        run: |
          echo "==> Checking linting with Ruff..."
          uv run --only-group dev ruff check .

      - name: Run mypy for type checking
        run: |
          echo "==> Running mypy for type checking..."
          uv run --only-group dev mypy .
