name: Security Scan

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  push:
    branches: [main]
  workflow_dispatch:  # Allow manual triggers

jobs:
  run-security-scans:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      
      - name: Add UV to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Check for vulnerabilities with Safety
        run: uv run --only-group security safety check --json --continue-on-error
        continue-on-error: true  # Don't fail workflow on vulnerabilities
      
      - name: Security linting with Ruff (Bandit rules)
        run: |
          uv run --only-group dev ruff check --select S --output-format json > ruff-security.json || true
        continue-on-error: true
      
      - name: Upload security reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: |
            ruff-security.json
          retention-days: 30